// <auto-generated />
using System;
using Infrastructure.partonair_v01.ORM.EFCore.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.partonair_v01.ORM.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501120240_UpdateRoleConstraint")]
    partial class UpdateRoleConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.partonair_v01.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("AnnouncementCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("announcement_created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("AnnouncementDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("announcement_description");

                    b.Property<DateTime?>("AnnouncementUpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("announcement_updated_at");

                    b.Property<string>("JobTag")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("job_tag");

                    b.Property<string>("SkillsRequired")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("skills_required");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_announcement_user");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements", (string)null);
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("blocked_at");

                    b.Property<string>("ContactMail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("contact_mail");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_name");

                    b.Property<Guid>("ContactReceiverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_contact_receiver");

                    b.Property<Guid>("ContactSenderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_contact_sender");

                    b.Property<string>("ContactStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("contact_status");

                    b.Property<bool?>("IsBlocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_blocked");

                    b.Property<bool?>("IsFriendly")
                        .HasColumnType("bit")
                        .HasColumnName("is_friendly");

                    b.HasKey("Id");

                    b.HasIndex("ContactReceiverId");

                    b.HasIndex("ContactSenderId", "ContactReceiverId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Contacts_Sender_Receiver");

                    b.ToTable("Contacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contacts_NoSelf", "[fk_contact_sender] <> [fk_contact_receiver]");

                            t.HasCheckConstraint("CK_Contacts_Status_Valid", "[contact_status] IN ('Pending','Accepted','Blocked','Refused')");
                        });
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("EvalReceiverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_eval_receiver");

                    b.Property<Guid>("EvalSenderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_eval_sender");

                    b.Property<string>("EvaluationCommentary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("evaluation_commentary");

                    b.Property<DateTime>("EvaluationCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("evaluation_created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("EvaluationUpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("evaluation_updated_at");

                    b.Property<byte>("EvaluationValue")
                        .HasColumnType("TINYINT")
                        .HasColumnName("evaluation_value");

                    b.HasKey("Id");

                    b.HasIndex("EvalReceiverId");

                    b.HasIndex("EvalSenderId");

                    b.ToTable("Evaluations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Announcements_EvaluationValue_Valid", "evaluation_value BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.Images", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<byte[]>("CvImageBits")
                        .HasColumnType("VARBINARY(MAX)")
                        .HasColumnName("cv_image_bits");

                    b.Property<Guid>("FkProfileUser")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_profile_user");

                    b.Property<byte[]>("ProfileImageBits")
                        .HasColumnType("VARBINARY(MAX)")
                        .HasColumnName("profile_image_bits");

                    b.Property<int?>("SizeCvImage")
                        .HasColumnType("int")
                        .HasColumnName("size_cv_image");

                    b.Property<int?>("SizeProfileImage")
                        .HasColumnType("int")
                        .HasColumnName("size_profile_image");

                    b.Property<string>("TypeCvImage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type_cv_image");

                    b.Property<string>("TypeProfileImage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type_profile_image");

                    b.HasKey("Id");

                    b.HasIndex("FkProfileUser")
                        .IsUnique();

                    b.ToTable("Images", null, t =>
                        {
                            t.HasCheckConstraint("CK_type_cv_image", "[type_cv_image] IN ('.jpg','.png','.svg','.jpeg','.webp','.pdf')");

                            t.HasCheckConstraint("CK_type_profile_image", "[type_profile_image] IN ('.jpg','.png','.svg','.jpeg','.webp')");
                        });
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.ProfileUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<DateTime>("ProfileCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("profile_created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ProfileDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("profile_description");

                    b.Property<DateTime?>("ProfileUpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("profile_updated_at");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("skills");

                    b.Property<byte>("Stars")
                        .HasColumnType("TINYINT")
                        .HasColumnName("stars");

                    b.Property<string>("UrlCv")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url_cv");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_user");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileUsers", (string)null);
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastConnection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_connection")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("mail");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("password_hashed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Visitor")
                        .HasColumnName("role");

                    b.Property<DateTime>("UserCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("user_created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("UserUpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("user_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role_Valid", "role IN ('Visitor', 'Employee', 'Company', 'Admin', 'Moderator')");
                        });
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.Announcement", b =>
                {
                    b.HasOne("Domain.partonair_v01.Entities.User", "User")
                        .WithMany("Announcements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ANNOUNCEMENT_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.Contact", b =>
                {
                    b.HasOne("Domain.partonair_v01.Entities.User", "ContactReceiver")
                        .WithMany("ContactsReceived")
                        .HasForeignKey("ContactReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CONTACT_RECEIVER");

                    b.HasOne("Domain.partonair_v01.Entities.User", "ContactSender")
                        .WithMany("ContactsSent")
                        .HasForeignKey("ContactSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CONTACT_SENDER");

                    b.Navigation("ContactReceiver");

                    b.Navigation("ContactSender");
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.Evaluation", b =>
                {
                    b.HasOne("Domain.partonair_v01.Entities.User", "Receiver")
                        .WithMany("EvaluationsReceived")
                        .HasForeignKey("EvalReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EVAL_RECEIVER");

                    b.HasOne("Domain.partonair_v01.Entities.User", "Sender")
                        .WithMany("EvaluationsSent")
                        .HasForeignKey("EvalSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EVAL_SENDER");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.Images", b =>
                {
                    b.HasOne("Domain.partonair_v01.Entities.ProfileUser", "ProfileUser")
                        .WithOne("Image")
                        .HasForeignKey("Domain.partonair_v01.Entities.Images", "FkProfileUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROFILE_USER");

                    b.Navigation("ProfileUser");
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.ProfileUser", b =>
                {
                    b.HasOne("Domain.partonair_v01.Entities.User", "User")
                        .WithOne("ProfileUser")
                        .HasForeignKey("Domain.partonair_v01.Entities.ProfileUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.ProfileUser", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("Domain.partonair_v01.Entities.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("ContactsReceived");

                    b.Navigation("ContactsSent");

                    b.Navigation("EvaluationsReceived");

                    b.Navigation("EvaluationsSent");

                    b.Navigation("ProfileUser");
                });
#pragma warning restore 612, 618
        }
    }
}
